// import { NextUIProvider } from "@nextui-org/react";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/src/components/Header";
import Footer from "@/src/components/Footer";

const poppins = Poppins({ weight: ["300", "500"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {/* <NextUIProvider> */}
        <Header />
        {children}
        <Footer />

        {/* </NextUIProvider> */}
      </body>
    </html>
  );
}
